### ISSUE TITLE
write function that takes a given block and parcel and returns a summary of that building

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HolyokeUrbanRenewal#10]
This function, perhaps called `summarize_building()` will take the output of `get_buildings()` (see #3) and generate a text string that summarizes the png files for that building. Example:

`summarize_building(block = "01", parcel = "02")` might return:

```
BLOCK 01, PARCEL 02 has 1 info file, 2 map files, and 2 photos.
```

**Comment by nicholasjhorton** [comment]
You'll want to coordinate any changes with @arogers24 and @tknightly24 to avoid merge conflicts with the https://github.com/STAT325-S24/HolyokeUrbanRenewal/blob/main/R/commands.R file.

First step would be to stub it out when they aren't pushing.

**Comment by nicholasjhorton** [comment]
@vnguyen24 and @FranciscoJFM02 can you please add your commits for this work (or your plans, if you don't have a commit) to this issue?

**Comment by nicholasjhorton** [comment]
Do you have any updates on this issue? Thanks in advance for any guidance, Nick

**Comment by nicholasjhorton** [comment]
Perhaps something like this (assuming here that you are passing the tibble for a building, which contains a row for each image:

```
summarize_property <- function(property) {
  info_num <- filter(property, type == "info") |> nrow()
  photo_num <- filter(property, type == "photo") |> nrow()
  map_num <- filter(property, type == "map") |> nrow()
  
    cat("For this property, there are:\n")
    cat("  ", info_num, "information page(s)\n")
    cat("  ", photo_num, "photo page(s)\n")
    cat("  ", map_num, "map page(s)\n")
}
```

This could be improved so that if there is one page, it outputs "page" but if more than one "pages".

**Comment by nicholasjhorton** [comment]
It may be helpful to check out how things are shaping up in the `get_buildings()` function: https://github.com/STAT325-S24/HolyokeUrbanRenewal/issues/3 and https://github.com/STAT325-S24/HolyokeUrbanRenewal/blob/main/R/commands.R

I'm imagining that your function would take `block` and `parcel` as inputs, filter the output of `get_buildings()` for that block and parcel combination, then save the result as `property`.

**Comment by FranciscoJFM02** [comment]
I added a draft of this function (see commits 7a19fd83794c4d6c60d94655f5968037dc8d7df9 and 33c302cd43c5e70a877ce8a27b49494d7a55895f, will most likely need a proofread

**Comment by vnguyen24** [comment]
We wrote the function to return a summary (with error checks). See 4e6a9e3c60642072e0af7aeacf027ebd7e92e0b4. Can you please review this issue @nicholasjhorton. Thank you!

**Comment by nicholasjhorton** [comment]
Nicely done!
