### ISSUE TITLE
transposing tibble of underscore locations

### ISSUE THREAD

**Issue by arogers24** [STAT325-S24/HolyokeUrbanRenewal#11]
Given the output of str_locate_all(...), how can we create a vector of just the 4th locations of underscores, i.e. (data[[1]][4], data[[2]][4], data[[3]][4], ...)?

**Comment by nicholasjhorton** [comment]
Here's a reprex which I think provides a solution to this:

``` r
suppressPackageStartupMessages(library(tidyverse))
#> Warning: package 'tidyr' was built under R version 4.3.2
locations <- stringr::str_locate(
  c("block_01_parcel_06A_info_01.png", "block_01_parcel_06_info_01.png"),
  "block_[0-9]{2}_parcel_[0-9A]{2,3}_")
locations
#>      start end
#> [1,]     1  20
#> [2,]     1  19
locations[,2]
#> [1] 20 19
```

<sup>Created on 2024-02-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
