### ISSUE TITLE
Wrangle assessed_value

### ISSUE THREAD

**Issue by jpapagelis24** [STAT325-S24/HolyokeUrbanRenewal#15]
We need to wrangle the `assessed_value` variable and decide what values we want to keep. Things to keep in mind:
1. There are multiple values, including individual values as well as total values
2. Some of the parcels have multiple properties, which account for multiple total assessed values (as well as a grand total).

**Comment by nicholasjhorton** [comment]
Example: "Wood house $500, Land, $1000, Total: 1500"

Example: two buildings given in two paragraphs: 

Possible things to create as new columns:

1. number of paragraphs (buildings?)Is it a parcel with more than one building? (implementation idea: number of newlines or numbers or such)
2. total assessed value (calculated)
3. is a house? or not? (implementation idea: `str_detect("[Hh]ouse")`

**Comment by Casey308** [comment]
Did 3 with https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/367f124e4cb5933c137c1e72f5938a9f37170ff5

**Comment by Casey308** [comment]
@jpapagelis24, did you commit the correct code for assessed value with https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/dbc592876222f68f7ecd9774b83712925aedea5d?  I thought we had something parsing numbers in there, and this current code isn't working for me.

**Comment by jpapagelis24** [comment]
@Casey308 Ah, it looks like I committed the wrong version earlier. Try pushing again!

**Comment by nicholasjhorton** [comment]
Can you please let me know if this is ready for me to review? Thanks in advance for any guidance, Nick

**Comment by jpapagelis24** [comment]
@nicholasjhorton Yes, I believe this is ready for review unless @Casey308 is working on anything. I don't think that it is possible to extract the number of buildings from `assessed_value`. The format is inconsistent (sometimes having the different buildings in different paragraphs, sometimes not) and different words represent each building type.

**Comment by nicholasjhorton** [comment]
Thanks for your work on this front. It sounds like the info will need to be hand curated. I'll take things from here.
