### ISSUE TITLE
Figure out which variables to keep in the dataset

### ISSUE THREAD

**Issue by jpapagelis24** [STAT325-S24/HolyokeUrbanRenewal#16]
There are lots of variables (including `land_data`, `damages`, `financial_information`, `building_data`, etc) that have only one or two entries with the rest of the values being na. Could we remove some of these or perhaps combine them into some miscellaneous remarks variable?

**Comment by nicholasjhorton** [comment]
I like the idea of combining these variables into miscellaneous remarks.

**Comment by nicholasjhorton** [comment]
I've collated the remarks and pushed the new spreadsheet.
