### ISSUE TITLE
Look at discrepancies within date_aquired

### ISSUE THREAD

**Issue by jpapagelis24** [STAT325-S24/HolyokeUrbanRenewal#17]
It seems like there are some dates that are in the future, such as "2026-01-14". Not sure if this was a mistake, but there could be other such errors.

**Comment by nicholasjhorton** [comment]
@jpapagelis24 wins the data consistency checking prize of the week (to be allocated next week).

These are Y2K issues two digit dates: we need to identify and extirpate! (start with a time series plot).

**Comment by arogers24** [comment]
Fixed! https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/6ecf673f85f19349eea257f0045af05d50c7bc6c
