### ISSUE TITLE
Clean up tax_amount

### ISSUE THREAD

**Issue by jpapagelis24** [STAT325-S24/HolyokeUrbanRenewal#18]
Mix of some numbers and words. Does not look very clean. It could be a good idea to extract the numbers we want and format them so they look like amounts.

**Comment by arogers24** [comment]
Use `str_detect(stuff, "exempt")` to extract exemptions into another column (via `mutate()`). Use `parse_number()` to extract first number in tax_amount (avoid issue with ($245.74 - 1 family)).

**Comment by nicholasjhorton** [comment]
Thanks for exploring this: I'll take things from here.

**Comment by nicholasjhorton** [comment]
I'm closing this now: it has potential for future work.
