### ISSUE TITLE
Update documentation for HolyokeUrbanRenewal

### ISSUE THREAD

**Issue by jpapagelis24** [STAT325-S24/HolyokeUrbanRenewal#19]
Update the documentation for the HolyokeUrbanRenewal dataset once wrangling is finished and we have decided which variables to keep in the dataset.

**Comment by nicholasjhorton** [comment]
Done via https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/321d96575c64af89a0441c552169a35ed46115fe
