### ISSUE TITLE
need to restore original spreadsheet and create new spreadsheet with Y2K changes

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HolyokeUrbanRenewal#20]
It looks like the original spreadsheet https://github.com/STAT325-S24/HolyokeUrbanRenewal/blob/main/data-raw/riverview_renewal_data_2024_02_27.xlsx was modified by this commit:

https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/6ecf673f85f19349eea257f0045af05d50c7bc6c

@arogers24 can you please:

1. restore the previous version of the spreadsheet (prior to the Y2K changes, #17) and
2. save the revised spreadsheet with a new date

This will help clarify the data provenance (and allow me to potentially add the Y2K fixes to the https://github.com/STAT325-S24/HolyokeUrbanRenewal/blob/main/data-raw/DATASET.R

Thanks in advance, Nick

**Comment by arogers24** [comment]
I've restored the data and changed the name https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/042fa551f6e153121bdb3d4a3bbd47996c051f45

**Comment by nicholasjhorton** [comment]
Many thanks!All the best,NickOn Mar 1, 2024, at 4:08 PM, arogers24 ***@***.***> wrote:﻿
I've restored the data and changed the name 042fa55
