### ISSUE TITLE
fix up DESCRIPTION file

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HolyokeUrbanRenewal#5]
This issue will be closed when the DESCRIPTION is updated to be accurate. This may require multiple steps (e.g., determining the authors of the package).

**Comment by FranciscoJFM02** [comment]
Added a preliminary description within the description file and added @vnguyen24 and @FranciscoJFM02 as authors in commit: a64c8950a72a1a3ec117670ee355452760042899. Still need other authors to add their information to the file.

**Comment by nicholasjhorton** [comment]
Nicely done: I'm closing this issue.

**Comment by nicholasjhorton** [comment]
Package check was failing due to DESCRIPTION syntax error: see https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/46791de620a862d04df4eed060f6d19c003dbc56
