### ISSUE TITLE
write function to return one of the scanned files from a specific building

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HolyokeUrbanRenewal#6]
This will require something like:

`get_filename(block, parcel, type, number)`

and will provide a filename so that the image can be accessed using that filename:

e.g., 

`system.file(package = "mosaic")`

Returns:

```
# The root of package 'mosaic'
[1] "/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/mosaic"

which can have the pathname `inst/extdata/block_12_parcel_02_map_02.png` or similar appended.

**Comment by nicholasjhorton** [comment]
@vnguyen24 @FranciscoJFM02 might you be willing to add his into your tasks for this week's sprint?

**Comment by nicholasjhorton** [comment]
this work will need to be coordinated with @arogers24 and @tknightly24: might the four of you find a time for a virtual meeting or check in via GitHub issues?

**Comment by nicholasjhorton** [comment]
@vnguyen24 and @FranciscoJFM02 do you have any updates on this front? 

I think that this function will be approximately 5-7 lines long (with more potentially if you wanted to check the calling routines, and more importantly, that the file exists).

**Comment by nicholasjhorton** [comment]
Here's a first cut at a `select_building()` function: this includes the filename. 

But perhaps the filename should also be given with the absolute pathname (`image_path`) since that will be needed later. Any thoughts @vnguyen24 and @FranciscoJFM02?

https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/2f3348d6bc4ac99434a25e9d49a6d6a6b7ed368e

**Comment by vnguyen24** [comment]
Hi @nicholasjhorton  I'm currently prepping for an exam tomorrow. Would it be ok if I take a lot at the tasks after the exam? Thank you!

**Comment by nicholasjhorton** [comment]
That sounds eminently workable. Best wishes for your exam!

**Comment by FranciscoJFM02** [comment]
Better late than never, the function added with commit: 72a89b506cb303f33b689a1892be53655bf9862f. It can be used to get the intended filename, which can be used to open the file.

**Comment by nicholasjhorton** [comment]
Thanks for your work on this front!
