### ISSUE TITLE
wrangle HolyokeUrbanRenewal data and update documentation

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT325-S24/HolyokeUrbanRenewal#8]
There's considerable work needed to get the data package `HolyokeUrbanRenewal` spreadsheet data into shape (and documented).

This issue will be closed when easy things are done, a comprehensive list of remaining variables that need attention is created, and `roxygen2::roxygenize()` is run and version number in `DESCRIPTION` incremented.

**Comment by nicholasjhorton** [comment]
Here's the output of `glimpse()` to give a rough sense of what's needed:

``` r
dplyr::glimpse(HolyokeUrbanRenewal::HolyokeUrbanRenewal)
#> Rows: 126
#> Columns: 32
#> $ file_name                              <chr> "block_02_parcel_01_info", "blo…
#> $ block                                  <dbl> 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3…
#> $ parcel                                 <chr> "1.0", "5.0", "1.0", "2.0", "3.…
#> $ property_location                      <chr> "Union & Prospect Streets", "We…
#> $ owner                                  <chr> "Whiting Oil Corp.", "Whiting O…
#> $ owner_address                          <chr> "1 Fountain Street, Holyoke, Ma…
#> $ data_acquired                          <chr> NA, NA, NA, "24651.0", "19854.0…
#> $ grantor                                <chr> NA, NA, NA, "Thomas & Alice Gig…
#> $ deed_reference_book                    <chr> NA, NA, NA, "3267.0", "2309.0",…
#> $ deed_reference_page                    <chr> NA, NA, NA, "489.0", "116.0", "…
#> $ tax_year                               <dbl> NA, NA, NA, 1969, 1969, 1969, 1…
#> $ tax_amount                             <chr> NA, NA, NA, "354.9", "373.1", "…
#> $ tax_remarks                            <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ assessed_value                         <chr> NA, NA, NA, "Wood Block - $2,40…
#> $ stamps                                 <chr> NA, NA, NA, "None", "8.25", "22…
#> $ remarks                                <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ building_description                   <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ type                                   <chr> "Garage & oil tanks", "Coal bun…
#> $ current_use                            <chr> "Fuel Oil & truck storage plant…
#> $ highest_and_best_use                   <chr> "Same", "Business", "Residentia…
#> $ zoning                                 <chr> "Business A", "Business A", "Bu…
#> $ appraisal_date                         <dttm> 1970-04-07, 1970-03-09, 1970-0…
#> $ approach_used                          <chr> "cost, market", "cost", "market…
#> $ value_estimate_total                   <dbl> 28000, 13500, 12000, NA, NA, NA…
#> $ value_estimate_before_taking           <dbl> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ value_estimate_after_taking            <dbl> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ damages                                <dbl> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ land_data                              <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ financial_information                  <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ site_descriptions                      <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ interpretations_of_site_maps_and_plans <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
#> $ building_data                          <chr> NA, NA, NA, NA, NA, NA, NA, NA,…
```

<sup>Created on 2024-02-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by nicholasjhorton** [comment]
@Casey308 and @jpapagelis24 at some point this evening can you please tag your commits here and share an update on what you have been doing (and what is planned)? 

I'm assuming that this will involve edits to https://github.com/STAT325-S24/HolyokeUrbanRenewal/blob/main/data-raw/DATASET.R

Thanks in advance, Nick

**Comment by nicholasjhorton** [comment]
In particular, I would encourage you to start to stub out issues for each of the remaining variables which need to be wrangled: we can tackle them via a divide and conquer approach. (All you two need to do is to outline the variable, what challenges there are, and share some thoughts (or not) about possible ways to address them.

**Comment by nicholasjhorton** [comment]
@Casey308 and @jpapagelis24 can you please share an update where this issue stands? I'm hoping that you can make some progress on some of the data wrangling and also create a set of new issues for variables that will not be straightforward to wrangle.

**Comment by nicholasjhorton** [comment]
See some minor tweaks here: can you please pull and let me know if you see any issues?

https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/76da836cdcf8f74b0de032b4d714a429aebf5fb3

**Comment by jpapagelis24** [comment]
@nicholasjhorton Fixed some of the formatting issues you commented with block and parcel. Still working on some of the other variables : d74bff034028ab51eeb94e59f4deb50d1835e041

**Comment by nicholasjhorton** [comment]
Thanks for your work on https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/d74bff034028ab51eeb94e59f4deb50d1835e041: I added some comments to that commit. Can you please review and let me know if you have any questions?

**Comment by nicholasjhorton** [comment]
I went ahead and updated the dataset to create the string `block` and `parcel` ids: see https://github.com/STAT325-S24/HolyokeUrbanRenewal/commit/66515412e672c37d9488c8335589e37b46160e69

My hope is that this issue can be replaced by any remaining data wrangling issues (as well as a new issue to update the documentation for the `HolyokeUrbanRenewal` dataset).

**Comment by jpapagelis24** [comment]
Created new issues that specify the individual tasks left to handle
