### ISSUE TITLE
Collapsing same blocks and parcels into one row

### ISSUE THREAD

**Issue by Casey308** [STAT325-S24/HolyokeUrbanRenewal#9]
@jpapagelis24 and I thought it may be useful to collapse block and parcels into one row when they have multiple rows.  For now this doesn't seem like a top priority, but at some point this could be something useful to work on.

**Comment by nicholasjhorton** [comment]
The example here is for blocks and parcels with more than one info page (e.g., 
![](https://github.com/STAT325-S24/HolyokeUrbanRenewal/blob/main/inst/extdata/block_15_parcel_07_info_02.png)
)

In the interim, can you create a variable that indicates whether this is an "info_1" page?

**Comment by jpapagelis24** [comment]
@nicholasjhorton added an indicator variable for "info_1" page: d74bff034028ab51eeb94e59f4deb50d1835e041

**Comment by nicholasjhorton** [comment]
My plan is to elide the multiple rows for a building from the spreadsheet: I'll take things from here.

**Comment by nicholasjhorton** [comment]
I also fixed this in the spreadsheet; thanks again for the guidance about what was needed.
